version: 2

project_name: icloud-reminders

before:
  hooks:
    - cd go && go mod tidy

builds:
  - id: reminders
    main: ./go
    binary: reminders
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - scripts/reminders.sh

# Separate archive for install script (version-independent URL)
release:
  extra_files:
    - glob: scripts/install.sh
      name_template: install.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew Tap configuration
# Requires GITHUB_TOKEN with repo access to the tap repository
brews:
  - name: icloud-reminders
    repository:
      owner: tarekbecker
      name: homebrew-tap
      token: '{{ .Env.TAP_GITHUB_TOKEN }}'
    url_template: 'https://github.com/tarekbecker/icloud-reminders-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: 'Brew formula update for {{ .ProjectName }} version {{ .Tag }}'
    homepage: 'https://github.com/tarekbecker/icloud-reminders-cli'
    description: 'CLI for managing Apple iCloud Reminders via CloudKit API'
    license: 'MIT'
    install: |
      bin.install 'reminders'
    test: |
      system '#{bin}/reminders', 'version'
